server:
  port: 8088
  host: 0.0.0.0

camera:
  width: 2592
  height: 1944
  quality: 70
  brightness: 50
  contrast: 0
  saturation: 0
  sharpness: 0
  iso: 0
  exposureMode: AUTO
  automaticWhiteBalance: AUTO
  encoding: JPEG

#  stereoscopic:
#    stereoscopicMode: NONE
#    decimate: false
#    swapEyes: false
#  videoStabilisation: false
#  shutterSpeed: 0
  exposureMeteringMode: MATRIX
#  exposureCompensation: 0
#  dynamicRangeCompressionStrength: OFF
#  automaticWhiteBalanceRedGain: 0.0
#  automaticWhiteBalanceBlueGain: 0.0
#  imageEffect: NONE
#  mirror: NONE
#  rotation: 0
#  corp:
#    cropX: 0.0
#    cropY: 0.0
#    cropW: 0.0
#    cropH: 0.0
#  colourEffect
#    enable: false
#    u: 0
#    v: 0
#  captureTimeout: 0
  delay: 0 #delay before taking the picture, specified in milliseconds
  cameraModeControlPin: 17
bh1750:
  moduleAddress: 0x23  #Default address for the GY-302 BH1750 module
bmep280:
  moduleAddress: 0x77
  forcedModeTimeout: 2000